### ISSUE TITLE
How to avoid the whole job exit when one task failed.

### ISSUE THREAD

**Issue by pincher-chen** [paddydoyle/staskfarm#2]
I found that if one task  failed, then the whole job exit:
```
srun: error: cn12973: tasks 2113,2118,2129-2130: Killed
```

how to avoid this case?

**Comment by paddydoyle** [comment]
Hi,

I don't see the same behaviour, at least with serial non-MPI tasks. When one of the multi-prog tasks exits with a non-zero exit status, the others appear to keep going.

Are you using MPI tasks in the staskfarm? What version of slurm are you running? 

Maybe it's a different slurm.conf setting. Does your site have 'KillOnBadExit=1' ? We have the default of 0 which allows other tasks to continue to run, even if one crashes.

Paddy
